services:
  frontend-react:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACK_END_URL:http://santiserver.nowddns.com:5005
  hot-to-code-api:
    build: ./server
    ports:
      - 5005:5005
    environment:
      - ORIGIN:*
      - TOKEN_SECRET:secret
    env_file:
      - .env
